### ISSUE TITLE
issue（MVP）

### ISSUE THREAD

**Issue by canopus222** [canopus222/sotu_app#62]
## 各種情報
サービスの概要とMVPで検証する事柄：電車の写真を投稿し共有できるアプリ。
サービス名：Trainspotter
サービスURL：https://trainspotter.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ログインログアウト
- [ ] 投稿の新規・編集・削除
- [ ] ユーザーの登録・編集・退会
READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
- [ ] バッジ機能追加
- [ ] 本リリース予定のいいねを実装
- [ ] 本リリース予定の投稿一覧を実装
- [ ] Googlemapの導入時クレジットカードの設定が何度やってもうまくいかず導入を断念
- [ ] Googlemap断念に伴い、地図関係はなしにして、駅での電車撮影を想定した電車投稿に変更

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有してください。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下の2点ご確認をお願いします。

1. 投稿に失敗したとき、都道府県が選べなくなってしまう
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/d213d268d4277266d678e59f1a686087.png)](https://startup-technology.gyazo.com/d213d268d4277266d678e59f1a686087)

2. 編集、削除のボタンが表示されているが「削除」「編集」の表記がない
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/4f8adf797cc93c2a2185b4284fcf251e.png)](https://startup-technology.gyazo.com/4f8adf797cc93c2a2185b4284fcf251e)

よろしくお願いします。

**Comment by canopus222** [comment]
- [ ] 上記2点修正しました。
- [ ] 加えて、「パスワード忘れた方はこちら」でメールアドレスを送信した時次のような画面になってしまっていたのを修正しました（本番環境での設定をしていなかったため発生したエラー）
[![Image from Gyazo](https://i.gyazo.com/6c169d292f5559c0878af07cef0c3096.png)](https://gyazo.com/6c169d292f5559c0878af07cef0c3096)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
